# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd48515a877f7655aaa287b80979b53bd52f20072f07a1a1d169c0e57634d3bf2a766a4622d22440ba8e52280ba2a1a5f6a58dd076a216b46db81c1be8e2c1cc

test:
  secret_key_base: b7a4f0d2d3d27d40999da22dcfeaf059b3d642617e897d842005631156564ff15726194960c345767d02353e4d8b8907e1dc1351338f18ae281f6db224911a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
